controlplaneio/kubesec

pkg/server/server.go
- Redirect HTTP GET calls to `/` and `/scan` to kubesec.io
- Redirect `/` HTTP POST to `/scan` (preserve v1 behaviour)
Fix: #43
=> Redirect HTTP GET calls to root and scan to main website

pkg/ruler/report.go, test/1_cli.bats
=> feat: add point field to json marshalling struct

cloudbuild.yaml
Updates for latest GCP cloud run configuration.
=> build: safe mode, update --platform flag

.markdownlint.yaml, .travis.yml, Makefile, README.md, code-of-conduct.md
Should check none of the markdown changes broke anything rendered from the markdown
=> Markdown linting fixes

MAINTAINERS, README.md, cmd/kubesec/scan.go, pkg/ruler/report.go, test/1_cli.bats
feat: extended rules/report to enable custom sort of report in scan fn
closes #44
=> Return rules in deterministic order

.travis.yml
=> fix: remove deploy from travis

Dockerfile
=> Update to Alpine 3.11

README.md, pkg/ruler/report.go, pkg/ruler/ruleset.go, test/1_cli.bats, test/2_regression.bats, test/3_todo.bats, test/asset/score-5-pod-serviceaccount.yml
* Added a passed section to the JSON
* shellcheck fixes
* moved some tests to use `jq` rather than fixed indexes
Resolves #93 #97 
---
Previous output:
```json
[
{
"object": "Pod/kubesec-demo.default",
"valid": true,
"message": "Passed with a score of 1 points",
"score": 1,
"scoring": {
"advise": [
{
"selector": ".metadata .annotations .\"container.apparmor.security.beta.kubernetes.io/nginx\"",
"reason": "Well defined AppArmor policies may provide greater protection from unknown threats. WARNING: NOT PRODUCTION READY",
"points": 3
},
{
"selector": ".spec .serviceAccountName",
"reason": "Service accounts restrict Kubernetes API access and should be configured with least privilege",
"points": 3
},
{
"selector": ".metadata .annotations …
```
=> Clearer points output

cloudbuild.yaml, test/0_test_deps.bats, test/2_regression.bats, test/_helper.bash
* Added `jq` to cloudbuild
* Cleaned up local and remote skips
=> Fix cloud build `jq` dependency

.editorconfig, README.md, cmd/kubesec/scan.go, test/2_regression.bats, test/_helper.bash
=> Support piping into kubesec with `-` and `/dev/stdin`

.deepsource.toml, cmd/kubesec/scan.go, pkg/ruler/ruleset.go, pkg/rules/apparmorAny.go, pkg/rules/seccompAny.go, pkg/rules/seccompUnconfined.go, pkg/server/server.go
This pull request fixes some of the quality issues raised by [DeepSource](https://deepsource.io/gh/sourya-deepsource/kubesec/) on my fork of this repository.
Some of the issues were automatically fixed by DeepSource, while I fixed others by hand.
1. Merge this PR. I have included a `.deepsource.toml` in this PR, which you can use to [configure](https://deepsource.io/docs/analyzer/go.html) your analysis settings.
2. Install DeepSource on your repository [here](https://deepsource.io/signup).
3. After signing up, activate analysis [here](https://deepsource.io/dashboard).
If you do not want to use DeepSource to continuously analyze this repo, I'll remove the `.deepsource.toml` from this PR and you can merge the rest of the fixes.
=> Fix code quality issues

.github/dependabot.yml, .github/workflows/codeql_analysis.yml, .github/workflows/release.yml
PR to add codeql scanning for go + dependabot version bumps for go, docker, gh actions
=> addding codeql & dependabot

.github/workflows/security_analysis.yml
=> chore: add trivy scanning

.gitignore, cmd/kubesec/scan.go, pkg/report/writer.go, pkg/ruler/report.go, pkg/ruler/rule.go, pkg/ruler/ruleset.go, pkg/server/server.go, templates/sarif.tpl, test/1_cli.bats, test/_helper.bash
=> Add template output and a valid sarif template

go.mod, go.sum, pkg/server/server.go
This is the sequel to #134 which bumps intoto and resolves the change to loading keys
Would be great to get a once over from @SantiagoTorres as while it builds and seems correct I haven't tested it yet.
=> bump intoto version

CHANGELOG.md
=> docs: add changelog update for 2.11.2

.github/dependabot.yml
=> chore: dependabot update all dependencies

README.md
this is the newer standard for installing binaries, so I updated accordingly
=> docs: use go install

go.mod, go.sum, pkg/ruler/ruleset.go, pkg/ruler/ruleset_test.go, test/2_regression.bats, test/_helper.bash, test/asset/multi.yml, test/asset/score-0-daemonset-host-network.yml, test/asset/score-0-daemonset-host-pid.yml, test/asset/score-0-daemonset-mount-docker-socket.yml, test/asset/score-0-daemonset-securitycontext-privileged.yml, test/asset/score-0-daemonset-volume-host-docker-socket.yml, test/asset/score-0-statefulset-no-sec.yml, test/asset/score-1-daemonset-default.yml, test/asset/score-1-dep-default.yml, test/asset/score-1-dep-empty-security-context.yml, test/asset/score-1-dep-invalid-security-context.yml, test/asset/score-1-dep-resource-limit-cpu.yml, test/asset/score-1-dep-resource-limit-memory.yml, test/asset/score-1-dep-ro-root-fs.yml, test/asset/score-1-dep-seccon-run-as-non-root.yml, test/asset/score-1-dep-seccon-run-as-user-1.yml, test/asset/score-1-dep-seccon-run-as-user-10001.yml, test/asset/score-1-statefulset-default.yml, test/asset/score-1-statefulset-volumeclaimtemplate.yml, test/asset/score-2-dep-serviceaccount.yml, test/asset/versioned/score-0-daemonset-v1.11.yml, test/asset/versioned/score-0-statefulset-v1.11.yml
acceptance tests failing, will look into that
Addresses issue #344, kubeval is not maintained and marks some valid YAML files as invalid. kubeconform is the recommended replacement and seems to work as intended for the YAML file in #315 that was causing the issue.
=> feat: issue #344 - replaced kubeval with kubeconform

.github/workflows/security_analysis.yml
Including Trufflehog github action into the security_analysis workflow for secrets detection in PRs, as mentioned in #129.
n/a
=> chore: added trufflehog github action for secrets scanning

README.md, cmd/http.go, pkg/server/server.go, pkg/util/util.go, pkg/util/util_test.go
- Fix port setting logic
- Deprecate usage of PORT in favor of KUBESEC_ADDR
- Update README
Resolves #510
=> feat: suport ip:port for http listener

.github/workflows/release_containers_webhook.yml
---
name: Pull Request
about: A pull request
title: ''
labels: ''
assignees: ''
---
=> chore: manual workflow for releasing kubesec-workflow for now

CHANGELOG.md
---
name: Pull Request
about: A pull request
title: ''
labels: ''
assignees: ''
---
=> docs: add release note for v2.14.2
