pkg/rules/capDropAll.go

Currently KubeSec only matches securityContext.capabilities.drop capital `ALL`. This is incorrect as a lower case `all` is perfectly fine. A lowercase `all` is for example used in the Coredns deployment manifest (my commit) or your documentation: https://kubesec.io/basics/containers-securitycontext-capabilities-drop-index-all/

make securityContext.capabilities.drop.ALL rule case insensitive

---

cloudbuild.yaml

This can be done in the cloudbuild console, but is safer in code IMHO.
Contributes towards https://github.com/controlplaneio/kubesec/issues/29 -- although need to add release process for tags.

feat: only push and deploy docker image from master

---

README.md
cloudbuild.yaml
pkg/ruler/ruleset.go
pkg/rules/allowPrivilegeEscalation.go
pkg/rules/allowPrivilegeEscalation_test.go
test/1_cli.bats
test/asset/allowPrivilegeEscalation.yaml

Closes https://github.com/controlplaneio/kubesec/issues/51
Score of `-7` is less than mounted Docker socket (`-9`) or `CAP_SYS_ADMIN` (`-30`). 
(Would like to review and publish the scores at some point, perhaps just adding them to the YAML output is a good start @stefanprodan?)

feat: add allowPrivilegeEscalation

---

Dockerfile.scratch

Not sure how we want to handle multiple Dockerfiles, automate the build, etc.
I'll post this as a draft for now. Suggestions for ^^^ welcome.
Output from `REMOTE_URL="http://localhost:8080" make test-remote` against the container running on `8080`
```
+ test-remote
bash -xc 'cd test && REMOTE_URL=http://localhost:8080 ./bin/bats/bin/bats  .'
1..48
ok 1 fails Pod with unconfined seccomp
ok 2 fails with CAP_SYS_ADMIN
ok 3 fails with CAP_CHOWN
ok 4 fails with CAP_SYS_ADMIN and CAP_CHOWN
ok 5 passes with securityContext capabilities drop all
ok 6 passes deployment with securitycontext readOnlyRootFilesystem
ok 7 passes deployment with securitycontext runAsNonRoot
ok 8 fails deployment with securitycontext runAsUser 1
ok 9 passes deployment with securitycontext runAsUser > 10000
ok 10 fails …
```

Scratch dockerfile

---

test/1_cli.bats
test/_helper.bash

When deployed to cloud run, the `make test-acceptance` test were asserting against the index of a specific line that was bumped by one due to `curl` debug output.
This change changes that debug to point to FD 3 (bats' debug output) and prefixes with a hash for TAP compliance. Then it comments out the debug because we don't need it.

test: ensure line assertions match local/remote

---

cloudbuild.yaml

This reduces the steps required and runs acceptance tests against production on every build

build: speed up cloudbuild, run acceptance tests

---

README.md
pkg/ruler/report.go
test/1_cli.bats
test/asset/critical-double.yml

Changed ordering from numeric to magnitude. Lowest numbered criticals first; highest advises first.

feat: magnitude ordering

---

cmd/kubesec/scan.go
pkg/ruler/ruleset.go
pkg/server/server.go
test/1_cli.bats
test/asset/critical-double-multiple.yml
test/asset/critical-double.yml

Adds multi-yaml (two yamls in one file split with '---') testing
Refactor duplicated report ordering code - sorting removed from scan/server and added into ruleset

Add multi-yaml test and move repeated sorting from scan/server into ruleset

---

.github/workflows/release.yml
.goreleaser.yml

Improve `.goreleaser.yml` file and add Github action based on goreleaser, in order to release binaries when a new tag is created with the format `v*.*.*`.
This solves issue https://github.com/controlplaneio/kubesec/issues/53.
Since `dep` is being used for dependencies management, and it forces to follow certain directory structure, some black magic needs to be done in file `release.yml`:
-  "Set GOPATH" step in order to set  GOPATH env to the folder where repository is going to be checked out.
- Check out the code under the following path: `${GOPATH}/src/github.com/controlplaneio/kubesec/`

Add github action based on goreleaser to release binaries

---

Gopkg.lock
cmd/kubesec/http.go
pkg/ruler/ruleset.go
pkg/ruler/ruleset_test.go
pkg/server/server.go

This PR adds support for generating signed reports as link metadata:
I.e., running your server with the newly optional flag `-k <path>` will let you answer to queries using the fragment `in-toto=` for the `scan` endpoint:
```
[santiago@LykOS kubesec]$ ./kubesec http 8080 -k somekey 
{"severity":"info","timestamp":"2019-11-11T13:15:55.934-0500","caller":"server/server.go:39","message":"Starting HTTP server on port 8080"}
```
To generate a link you simply can: 
```
[santiago@LykOS kubesec]$ curl --data "$(cat test/asset/score-1-dep-default.yml )" localhost:8080/scan?in-toto=1 | jq .link
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  3771    0  3562  100   209    692     40  0:00:05  0:00:05 --:--:--   902
{ …
```

server: add in-toto support

---

README.md
go.mod
pkg/server/server.go
test/2_regression.bats
test/asset/form-prefix-file.json
test/asset/form-prefix-file.yml
test/asset/form-prefix-not-file.json
test/asset/form-prefix-not-file.yml

This fix allows for the use of forms and to keep the current non-standard usage of curl avoiding breaking changes.
The current usages of curl in the README and elsewhere provide raw data with a content-type header saying it's form data. This is non-standard behavior and should be fixed in v3 to correctly parse data as is stated in the header.
Because adhering to the content-type header would be a breaking change we have opted for this backwards compatible bug fix for now of stripping the `file=` prefix if it exists.

81 fix website linting demo

---

README.md

Visiting https://kubesec.io gave me the warning "Mixed Content: The page at 'https://kubesec.io/' was loaded over HTTPS, but requested an insecure image 'http://casual-hosting.s3.amazonaws.com/kubesec-logo.png'. This content should also be served over HTTPS."
The logo itself is available via https. Changing the protocol might fix the warning.

Moved kubesec-logo to https

---

pkg/ruler/ruleset.go

Small misc fixes to the in-toto link attestation generation to ensure
compatibility with the python implementation.
(Also, pass gofmt checks).

ENH: in-toto: ensure signatures are cross-platform

---

cmd/kubesec/scan.go
pkg/ruler/ruleset.go
pkg/ruler/ruleset_test.go
pkg/server/server.go
test/2_regression.bats

Resolves #120
Empty and header only yaml docs are now ignored. Still errors if there are no reports
Also corrected the file name passed to kubeval so errors are nicer.
Added a flag for absolute file names too.

fix: account for multi doc yaml splitting issues

---

.github/workflows/release.yml
.github/workflows/security_analysis.yml

resolves #132 
Also pins the goreleaser version (so it can be bumped by PR by dependabot)

pin goreleaser and update codeql changed requirements

---

cmd/scan.go
pkg/ruler/ruleset.go
pkg/ruler/ruleset_test.go
pkg/server/server.go

With the current implementation the directory in which the schema files may reside is pinned to ("/schemas"). 
However, in some instances  (i.e. read-only file systems of a serverless function), it is not possible to place the schema files directly under the root folder ("/schemas"). Furthermore, always downloading the schemas is also not viable in a restricted environment.

Allow specifying the location of schema files

---

pkg/ruler/ruleset.go

Predicate and ID is incorrect in the definition of limitsMemoryRule (most likely a copy-paste error).

Rule "LimitsMemory" is missing in ruleset.go

---

Dockerfile
Makefile
README.md
cmd/http.go
cmd/scan.go
pkg/ruler/ruleset.go
pkg/ruler/ruleset_test.go
pkg/ruler/schema.go
pkg/ruler/schema_test.go
pkg/server/server.go

Since the migration to kubeconform, the flag `--schema-dir` does not have any effect when provided. This commit replaces it with the flag `--schema-location` that can be used to provide the schema remotely with http or locallly.
This commit also adds an option to disable the schema validation. This will be useful when we will use kubesec as a library for kubectl-kubesec and kubesec-webhook. For these projects, we are getting the object from the cluster so we know the object is properly formated.
Signed-off-by: ludo <controlplane@spiarh.fr>

fix: ensure json schema location can be configured

---

pkg/ruler/ruleset.go
pkg/rules/procMount.go
pkg/rules/procMount_test.go

Hello, I've noticed that kubesec isn't reacting at mount /proc. This is a potentially big issue for me cause I want to be able to check whether /proc mounted or not
P.S. I'm not a developer feel free to correct my copy-paste code :)

fix: add proc rule

---

.goreleaser.yml

Adding the missing "ldflags" section fixes the following issues:
Fixes https://github.com/controlplaneio/kubesec/issues/250
Fixes https://github.com/controlplaneio/kubesec/issues/337
FYI @06kellyjac 
I've validated this fix locally:
```
$ goreleaser build --snapshot --clean
• starting build...
• loading config file                              file=.goreleaser.yml
• loading environment variables
• getting and validating git state
• ignoring errors because this is a snapshot     error=git doesn't contain any tags. Either add a tag or use --snapshot
• building...                                    commit=5fc3bd266ec4e88f121f3ac168ad88ec9dcd895a latest tag=v0.0.0
• pipe skipped                                   reason=disabled during snapshot mode
• parsing tag
• setting defaults
• running …
```

Properly inject missing version/date/commit variables

---

.github/workflows/security_analysis.yml

Some actions need setup or to submit data that only work on the original repo and not on forks
---
Created the PR from a fork rather than in repo as-per-usual to test the changes

chore: stop actions from failing on forks

---

pkg/ruler/ruleset.go
pkg/rules/automountServiceAccountToken.go
pkg/rules/automountServiceAccountToken_test.go
test/1_cli.bats
test/asset/score-1-pod-automount-sa-set-to-false.yml

- check if automountServiceAccountToken is set/unset in Pods, Deployments, DaemonSets, and StatefulSets
- add unit tests for Pods, Deployments, DaemonSets, and StatefulSets to validate the behavior of the automountServiceAccountToken field

feat: check automountServiceAccountToken  across K8s resources

---

.github/workflows/release.yml
.github/workflows/security_analysis.yml
.github/workflows/test_acceptance.yml
.github/workflows/test_unit.yml
Makefile
go.mod
go.sum
test/2_regression.bats

Also pull go version from go mod file

chore: update go dependencies and go

---

pkg/ruler/ruleset.go
pkg/rules/hostUsers.go
pkg/rules/hostUsers_test.go
test/1_cli.bats
test/asset/score-1-pod-hostUsers-set-to-false.yml

- In Kubernetes v1.33 support for user namespaces is enabled by default. The new kubesec rule checks if a Pod is running in user namespace instead of host namespace.
[contributing]: https://github.com/controlplaneio/kubesec/blob/master/CONTRIBUTING.md

feat: check if a Pod is running in user namespace
